name: secrets-using-gitleaks

on:
  workflow_dispatch:

jobs:

  Secrets:
 
    runs-on: ubuntu-latest

    steps:

# ~~~~~~~~~~~~~~~~~~~ Dumping Code ~~~~~~~~~~~~~~~~~~~

      - name: Dumping Source Code
        uses: actions/checkout@v3

# ~~~~~~~~~~~~~~~~~~~ Secret Scanning ~~~~~~~~~~~~~~~~~~~

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
