name: test-scan

on:
  workflow_dispatch:

jobs:

  Secrets:
 
    runs-on: ubuntu-latest

    steps:

      - name: Dumping Source Code
        uses: actions/checkout@v3
#~~~~~~~~~~ Running Dependency Scan ~~~~~~~~~~
        
      - name: Dependency Scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan,nodejs"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

#~~~~~~~~~~ Uploading Results ~~~~~~~~~~

      - name: Uploading Scan Reports 
        uses: actions/upload-artifact@v1
        with:
          name: Dependency-and-Secret-Reports
          path: reports
